#!/bin/sh

# 等待Hub启动并生成root.json
echo "Waiting for root.json to be generated by hub..."
while [ ! -f /permit/root.json ]; do
  echo "Waiting for /permit/root.json..."
  sleep 5
done

echo "Found root.json, copying to ztm-permit.json"
cp /permit/root.json /permit/ztm-permit.json

echo "Starting ztm agent..."
exec /usr/local/bin/ztm run agent --listen 0.0.0.0:${ZTM_PORT:-7777} --data ${ZTM_DATA:-/home/ztm/.ztm} --permit /permit/ztm-permit.json --join ${ZTM_JOIN_MESH} --join-as ${ZTM_ENDPOINT}